### ISSUE TITLE
#28 "Not Responding" Issue

### ISSUE THREAD

**Issue by JaneraSmith** [JACorley1/UWG-SE2-Spring22-Team2#29]
#28 When I create a new account, the window was not responding. It was taking a long time to process. I ran it through maven and I saw that the request was successfully sent, however, it's not responding. That was an issue that I'm seeing now.

_Originally posted by @JaneraSmith in https://github.com/JACorley1/UWG-SE2-Spring22-Team2/issues/28#issuecomment-1091015550_

**Comment by Dowee2** [comment]
This issue occurs because the server.py is not  running. This leads to the client waiting for a response to their and the window not responding. Run server.py before launching client and this should resolve the issue
